### ISSUE TITLE
Allow origin in same domain

### ISSUE THREAD

**Issue by sheng-ri** [mythal/boluo#541]
https://github.com/mythal/boluo/blob/10cb423a6bac76713bd63b1a87fc6daca1ad87e2/apps/server/src/cors.rs#L17
This line make domain must be a sub domain.

其实我尝试在一台机子上部署spa/site/server,使用端口来处理不同的endpoint,但是这行就导致我无法取巧使用`地址:端口`来处理跨站

**Comment by uonr** [comment]
@sheng-ri 

如果是 localhost 或者 127.0.0.1 是允许的，你是想要用外部或者内网的IP而不是域名来部署吗？这样的话我觉得可以修改一下这个地方加个环境变量允许你需要的外部IP

**Comment by sheng-ri** [comment]
> @sheng-ri
> 
> 如果是 localhost 或者 127.0.0.1 是允许的，你是想要用外部或者内网的IP而不是域名来部署吗？这样的话我觉得可以修改一下这个地方加个环境变量允许你需要的外部IP

是的,我是想用地址来部署

**Comment by uonr** [comment]
> > @sheng-ri
> > 如果是 localhost 或者 127.0.0.1 是允许的，你是想要用外部或者内网的IP而不是域名来部署吗？这样的话我觉得可以修改一下这个地方加个环境变量允许你需要的外部IP
> 
> 是的,我是想用地址来部署

修改了一下 CORS 的逻辑，你在 DOMAIN 环境变量里填写你的外部IP应该就行
